# Generated by Django 4.2.7 on 2025-10-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
    ]
