# Generated by Django 4.2.7 on 2025-10-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20251031_1755'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create default profiles for existing users
            INSERT INTO recommender_profile (user_id, name, profile_type, is_active, created_at)
            SELECT id, 'Default', 'adult', 1, datetime('now')
            FROM auth_user
            WHERE NOT EXISTS (
                SELECT 1 FROM recommender_profile WHERE recommender_profile.user_id = auth_user.id
            );
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """
            -- Migrate existing UserRating records to use the default profile
            UPDATE recommender_userrating
            SET profile_id = (
                SELECT id FROM recommender_profile
                WHERE recommender_profile.user_id = recommender_userrating.user_id
                AND recommender_profile.is_active = 1
                LIMIT 1
            )
            WHERE profile_id IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
